server:
  port: 16000
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 100
        min-idle: 0
        max-idle: 8
    database: 0



